# Generated by Django 5.2.10 on 2026-01-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_focus_created_at_focus_enabled_focus_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name_plural': 'Expertise'},
        ),
        migrations.AlterModelOptions(
            name='focus',
            options={'verbose_name_plural': 'Focus'},
        ),
    ]
